# Generated by Django 5.0.1 on 2024-07-13 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminregister',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
