# Generated by Django 5.0.1 on 2024-07-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoi_app', '0003_alter_superadminregister_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='billingAgentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('datetime', models.TextField(blank=True, null=True)),
                ('rollid', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
