# Generated by Django 5.0.1 on 2024-07-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoi_app', '0004_billingagentregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctioninformationRegistertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManaMaganName', models.TextField(blank=True, null=True)),
                ('ManaMagalName', models.TextField(blank=True, null=True)),
                ('FucntionDate', models.TextField(blank=True, null=True)),
                ('FucntionLocationAddress', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
