# Generated by Django 5.0.1 on 2024-07-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoi_app', '0005_functioninformationregistertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioninformationregistertable',
            name='billingAgentPrimarykey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
