# Generated by Django 5.0.1 on 2024-07-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoi_app', '0006_functioninformationregistertable_billingagentprimarykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoiDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moi_user_Name', models.TextField(blank=True, null=True)),
                ('Moi_user_address', models.TextField(blank=True, null=True)),
                ('Moi_user_occupation', models.TextField(blank=True, null=True)),
                ('Moi_user_amount', models.TextField(blank=True, null=True)),
                ('FunctionInformationPrimaryKey', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
