# Generated by Django 5.0.1 on 2024-07-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoi_app', '0007_moidetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='moidetails',
            name='Moidetails_Datetime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
